Add support for NovaSeq X
Molmed/checkQC pull request #105
Opened 2023-05-02 13:58 UTC by Aratz

This PR adds a class for the NovaSeq X and make the code from this file leaner.

2023-05-03 10:19 UTC, matrulda requested changes
Great work! Left a lot of comments, but it's all basically based on changing the instrument name.

2023-05-03 10:19 UTC, matrulda commented on checkQC/run_type_recognizer.py
> +                return instrument_class()
Ah cool, this is very neat :ok_hand:

2023-05-03 10:19 UTC, matrulda commented on README.md
> + - NovaSeq X
This should be NovaSeq X Plus, the NovaSeq X has other specs and we are not sure that the instrument code for that system is LH.

2023-05-03 10:19 UTC, matrulda commented on checkQC/run_type_recognizer.py
> +class NovaSeqX(IlluminaInstrument):
```suggestion
class NovaSeqXPlus(IlluminaInstrument):
```

2023-05-03 10:19 UTC, matrulda commented on checkQC/run_type_recognizer.py
> +        return "novaseqx"
Should be novaseqxplus / novaseq_x_plus / novaseqXPlus. To stay true to the format with Miseq I would suggest the middle option: `novaseq_x_plus`, but I have no strong opinions about this.

2023-05-03 10:19 UTC, matrulda commented on checkQC/run_type_recognizer.py
> +                if consumable['Type'] == 'Reagent'
In the examples I've seen , it looks like `Mode` is the same in all consumables, so it should not matter, but personally I think it would make more sense to take it from the `FlowCell` consumable, since the ID we are fetching (<number>B) is the name of the flowcell.

2023-05-03 10:19 UTC, matrulda commented on checkQC/run_type_recognizer.py
> +            raise ReagentVersionUnknown("Could not identify flowcell mode for NovaseqX")
```suggestion
            raise ReagentVersionUnknown("Could not identify flowcell mode for NovaSeqXPlus")
```

2023-05-03 10:19 UTC, matrulda commented on checkQC/run_type_recognizer.py
> +            "LH": NovaSeqX,
```suggestion
            "LH": NovaSeqXPlus,
```

2023-05-03 10:19 UTC, matrulda commented on tests/test_run_type_recognizer.py
> +from checkQC.run_type_recognizer import RunTypeRecognizer, HiSeq2500, MiSeq, NovaSeq, ISeq, NovaSeqX
```suggestion
from checkQC.run_type_recognizer import RunTypeRecognizer, HiSeq2500, MiSeq, NovaSeq, ISeq, NovaSeqXPlus
```

2023-05-03 10:19 UTC, matrulda commented on tests/test_run_type_recognizer.py
> +        self.novaseqx = NovaSeqX()
```suggestion
        self.novaseqxplus = NovaSeqXPlus()
```

2023-05-03 10:19 UTC, matrulda commented on tests/test_run_type_recognizer.py
> +    def test_novaseqx_reagent_version(self):
```suggestion
    def test_novaseqxplus_reagent_version(self):
```

2023-05-03 10:19 UTC, matrulda commented on tests/test_run_type_recognizer.py
> +        actual = self.novaseqx.reagent_version(mock_runtype_recognizer)
```suggestion
        actual = self.novaseqxplus.reagent_version(mock_runtype_recognizer)
```

2023-05-03 10:19 UTC, matrulda commented on tests/test_run_type_recognizer.py
> +    def test_novaseqx_reagent_version_raises(self):
```suggestion
    def test_novaseqxplus_reagent_version_raises(self):
```

2023-05-03 10:19 UTC, matrulda commented on tests/test_run_type_recognizer.py
> +            self.novaseqx.reagent_version(mock_runtype_recognizer)
```suggestion
            self.novaseqxplus.reagent_version(mock_runtype_recognizer)
```

2023-05-03 11:09 UTC, Aratz commented on README.md
> + - NovaSeq X
Ah good point, will change :+1:

2023-05-03 11:21 UTC, Aratz commented on checkQC/run_type_recognizer.py
> +        return "novaseqx"
I'm not sure I follow, isn't the format for MiSeq just "miseq"? (https://github.com/Molmed/checkQC/blob/master/checkQC/run_type_recognizer.py#L99) In that case wouldn't `novaseqxplus` be the best option?

2023-05-03 12:05 UTC, matrulda commented on checkQC/run_type_recognizer.py
> +        return "novaseqx"
Ah you are right :+1: I agree

2023-05-04 06:13 UTC, matrulda approved these changes
Awesome! :+1: When Sara's PR is merged we can make a release candidate.

2023-05-04 06:14 UTC, merged