Adding a handler for the error rate
Molmed/checkQC pull request #17
Opened 2017-09-15 08:29 UTC by johandahlberg

This adds a error rate handler.

2017-09-15 13:02 UTC, monikaBrandt commented on tests/handlers/test_error_rate_handler.py
> +        qc_config = {'name': 'ErrorHandler', 'error': 3, 'warning': 5}
The level of failure should be higher than the level of warning.

2017-09-15 13:06 UTC, monikaBrandt requested changes
Please, update warning and error levels in test_error_rate_handler.py

2017-09-18 07:53 UTC, johandahlberg commented
Fixed.

2017-09-18 08:22 UTC, monikaBrandt approved these changes

2017-09-18 08:24 UTC, monikaBrandt commented
Awesome! Everything looks good.

2017-09-18 08:24 UTC, merged